### ISSUE TITLE
Exe path?

### ISSUE THREAD

**Issue by alexcroox** [mjhasbach/MS-Task#1]
I'm trying to find out if a process is running or not, but I can have multiple copies of this process name and I need to pick the one with a certain path. None of the example functions expose a process path, only it's name (test.exe). Is there a way to obtain the execution paths too?

**Comment by mjhasbach** [comment]
Not possible with tasklist / taskkill, but it can be done with WMIC. See [node-ms-wmic](https://github.com/mjhasbach/node-ms-wmic):

```
wmic.process.list({executablePath: 'C:\\\\PATH\\\\TO\\\\EXE'}, function(err, processes) {
    if (err) {
        console.error(err);
    }

    console.log(processes);
});
```
